name: Bot Soiree Auto
on:
  schedule:
    - cron: '0 17 * * *' # Se lance à 17h00 UTC
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python soiree.py
